os: linux
language: python
dist: xenial
jobs:
  include:
    - name: Minimum NEP 029 versions
      python: 3.6
      env: NUMPY_VER=1.16
    # Versions with latest numpy
    - python: 3.6
    - python: 3.7
    - python: 3.8

services: xvfb

addons:
  apt:
    packages:
    - gfortran

before_install:
  # Unless version is specified, make sure travis uses latest numpy,
  # not pre-installed version
  # Latest releases of cftime, etc, not compatible with numpy 1.15
  - if [ -z ${NUMPY_VER} ]; then
      pip install -q numpy --upgrade;
    else
      pip install -q numpy==$NUMPY_VER;
      pip install "cftime<1.1";
      pip install "netCDF4<1.5.3";
      pip install "matplotlib<3.3";
    fi
  - pip install pytest-cov
  - pip install pytest-flake8
  - pip install coveralls
  - pip install future

install:
  - python setup.py install

before_script:
  # set up display screen
  - export DISPLAY=:99.0

script:
  - pytest -vs --flake8 --cov=sami2py/

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
